# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 08:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('tel', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^(13\\d|14[5|7]|15\\d|166|17[3|6|7]|18\\d)\\d{8}$', '手机号码格式错误')], verbose_name='手机号码')),
                ('password', models.CharField(max_length=64, verbose_name='登录密码')),
                ('born', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3)),
                ('school', models.CharField(blank=True, max_length=20, null=True, verbose_name='学校名字')),
                ('hometown', models.CharField(blank=True, max_length=200, null=True, verbose_name='家乡')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'reg-login',
            },
        ),
    ]
