# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180922_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_login',
            name='head',
            field=models.ImageField(default='image/shop3.png', upload_to='user/%Y%m/%d', verbose_name='用户头像'),
        ),
    ]
