# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_reg_login_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reg_login',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
