# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='res_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号码')),
                ('password', models.CharField(max_length=100, verbose_name='登录密码')),
            ],
            options={
                'db_table': 'res-login',
            },
        ),
    ]
