# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 03:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='活动名称')),
                ('image', models.ImageField(upload_to='activity/%Y%m/%d', verbose_name='活动图片')),
                ('url', models.CharField(max_length=200, verbose_name='地址')),
            ],
            options={
                'verbose_name': '首页活动',
                'verbose_name_plural': '首页活动',
                'db_table': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='Activity_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('describ', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_on_sale', models.BooleanField(choices=[(0, '下架'), (1, '上架')], default=0, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '首页活动专区',
                'verbose_name_plural': '首页活动专区',
                'db_table': 'Activity_area',
            },
        ),
        migrations.CreateModel(
            name='Activity_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Activity_area', verbose_name='专区id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('image', models.ImageField(upload_to='broadcast/%Y%m/%d', verbose_name='轮播图')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
                'db_table': 'Broadcast',
            },
        ),
        migrations.CreateModel(
            name='Goods_album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('image_addr', models.ImageField(upload_to='goods/%Y%m/%d', verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '商品相册',
                'verbose_name_plural': '商品相册',
                'db_table': 'Goods_album',
            },
        ),
        migrations.CreateModel(
            name='Goods_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cate_name', models.CharField(max_length=50, verbose_name='分类名')),
                ('cate_synopsis', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'Goods_category',
            },
        ),
        migrations.CreateModel(
            name='Goods_sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('synopsis', models.CharField(blank=True, max_length=100, null=True, verbose_name='简介')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='商品价格')),
                ('Stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales_volume', models.IntegerField(default=0, verbose_name='销量')),
                ('LOGO', models.ImageField(upload_to='goods/%Y%m/%d', verbose_name='logo图片')),
                ('grounding', models.BooleanField(choices=[(0, '下架'), (1, '上架')], default=0, verbose_name='是否上架')),
                ('goods_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_category', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品sku',
                'verbose_name_plural': '商品sku',
                'db_table': 'Goods_sku',
            },
        ),
        migrations.CreateModel(
            name='Goods_spu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spu_name', models.CharField(max_length=20, verbose_name='商品spu名称')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品详情')),
            ],
            options={
                'verbose_name': '商品spu',
                'verbose_name_plural': '商品spu',
                'db_table': 'Goods_spu',
            },
        ),
        migrations.CreateModel(
            name='Goods_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('unit_name', models.CharField(max_length=10, verbose_name='单位名')),
            ],
            options={
                'verbose_name': '商品单位',
                'verbose_name_plural': '商品单位',
            },
        ),
        migrations.AddField(
            model_name='goods_sku',
            name='goods_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_spu', verbose_name='商品spu'),
        ),
        migrations.AddField(
            model_name='goods_sku',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_unit', verbose_name='商品单位'),
        ),
        migrations.AddField(
            model_name='goods_album',
            name='goods_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_sku', verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='good_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_sku', verbose_name='商品sku_id'),
        ),
        migrations.AddField(
            model_name='activity_goods',
            name='goods_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_sku', verbose_name='专区商品sku_id'),
        ),
    ]
